### ISSUE TITLE
`.from(table).delte()` not returning an error?

### ISSUE THREAD

**Issue by bennik88** [supabase/postgrest-js#307]
# Bug report

## Describe the bug
When I'm deleting a row in my supabase table with `.from(table).delte().eq("id", id);` the function is not returning an error when trying to access a resource the user is not allowed access to.
I set up a table with a test row to delete and it worked. Then I set up `RLS` to make sure I catch any error that might happen. Therefore on purpose didn't set up an `RLS` for a row `DELETE` operation.
When I try to run the below code on the client side it works without throwing any error. Why is it not throwing an error if the user attempts to access a resource he has no access to?
If I have an error at the moment, it seems like sometimes the error is in `const { data, error }` and sometime in the `catch (err)` block. Is there any logic to it I'm missing on when to catch an error where?

## To Reproduce

**Create a delete function:**
```javascript
async function deleteContact(id: string) {
    if (!id) throw Error("Can't delete contact of none.");
    console.log("delete Contact");
    try {
      const { data, error } = await supabase
        .from("contacts")
        .delete()
        .eq("id", id);
      if (error) {
        console.log("error", error);
        throw Error(error);
      }
      return;
    } catch (err) {
      console.log("catchErr", err);
    }
  }
```

Enable `RLS` for the table you're trying to access.

## Expected behavior
Throwing an Error 403 instead of protecting from deletion and returning no error.

This would help in general to display valuable messages for the front-end user and also help to work with libraries like TanStack React-Query. Which expects:

A function that returns a promise that:
Resolves the data, or
Throws an error

## System information

- OS: macOS
- Browser: Chrome
- Version of supabase-js: "@supabase/supabase-js": "^2.0.0-rc.2",
- Version of React: "react": "18.2.0",
- Version of Next.js: "next": "12.2.4",

Thank you in advance.

**Comment by soedirgo** [comment]
> Then I set up RLS to make sure I catch any error that might happen. Therefore on purpose didn't set up an RLS for a row DELETE operation.
When I try to run the below code on the client side it works without throwing any error. Why is it not throwing an error if the user attempts to access a resource he has no access to?

When you enable RLS, it's restrictive by default - i.e. if there are no policies it'll act as if you have only one policy with the definition of `false`.

At the same time, a `DELETE` policy only affects *visibility* - with no policies in place, the `DELETE` "sees" an empty table, and thus finds no rows to delete, succeeding with a 204 No Content. Instead of returning an error when it tries to delete rows it has no access to, it can't even "see" the rows - returning an error is a security issue because attackers could find out which valid `id`s exist in the db by trying to delete one by one.

> If I have an error at the moment, it seems like sometimes the error is in const { data, error } and sometime in the catch (err) block. Is there any logic to it I'm missing on when to catch an error where?

It should always return the error instead of throwing it - having the error thrown might signal a bug.
