### ISSUE TITLE
.range() should give end of list flag

### ISSUE THREAD

**Issue by riancz** [supabase/postgrest-js#338]
# Feature request

## Is your feature request related to a problem? Please describe.

Not a problem per se.
Use case: when having a lazy load for data, lets say comments (when reaching the end of page or clicking button "load more").

## Describe the solution you'd like

Getting flag in the return payload received from query requests with .range() letting us know we reached the end of list and there is not more to fetch.

## Describe alternatives you've considered

- **Loading COUNT of rows and then keep track of reaching the end.** - Not a good solution because it takes unnecessary call.
- **Loading one more to see if I receive more rows and if not I can stop loading** - Not a good solution because user is expecting data when shown loader or when clicking on "load more" manualy.

**Comment by soedirgo** [comment]
This can be done by querying one more item than we're actually using, e.g. instead of `range(0, 9)`, `range(10, 19)`, etc., do `.range(0, 10)`, `.range(10, 20)`, etc. and ignore the last item.

To check if we are at the end, just do `data.length` - in this case we are at the end if and only if `data.length === 11`.
