### ISSUE TITLE
findOrCreate Method

### ISSUE THREAD

**Issue by jdcauley** [supabase/postgrest-js#339]
# Feature request

## Is your feature request related to a problem? Please describe.
While working on a project that leverages inbound hooks I find that I need to regularly leverage a function that is essentially a `findOrCreate` operation. It is frequent enough that I’m wondering if it would be considered for inclusion in the Supabase client

## Describe the solution you'd like
The ability to run a findOrCreate operation against a value and additional arguments.

The function would either return existing data from a matching key or create that value and return the inserted object.

## Describe alternatives you've considered
I am presently writing helper functions that preforms a fetch operation ahead of an insert operation to check for existing values.

I have checked the docs search but nothing has popped up in issues or docs that I found. If this exists and I missed it, I apologize in advance. 

## Additional context
This is particularly valuable when dealing with webhook based endpoints to help manage idempotency

**Comment by soedirgo** [comment]
Sorry for the super late reply!

Unfortunately I don't think this is something that can be supported by the client lib itself - it needs to be supported by the upstream REST server ([PostgREST](https://github.com/postgrest/postgrest)), you might have better luck creating a feature request there.

The alternative I recommend is exactly what you're doing, i.e. doing the logic in an `rpc`. Or if your use case is simple enough, you can try `upsert()`, specifying only the primary key:

```sql
create table my_table (
  id int8 primary key,
  created_at timestamptz default now()
);
```

```ts
const { data, error } = await supabase
  .from('my_table')
  .upsert({ id: 42 })
  .select()
```

The limitation is you need to rely on default values on `create` - you can't supply other columns or it'll overwrite them. i.e. this is `updateOrCreate` and `find` the new/updated row, instead of `findOrCreate`.
