### ISSUE TITLE
Update method doesn't work with React

### ISSUE THREAD

**Issue by Laplo** [supabase/postgrest-js#5]
Hi, I was trying your solution earlier this morning but I can't figure out why the update method doesn't work with React.
When trying the update method, OPTIONS pass and return a 200 but PATCH is never called (can't see it in my network tab) and the error which is shown is : "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:4000/omega?id=eq.15f65a8a-3d84-4a64-add6-d00bb1b698c4. (Reason: CORS request did not succeed)."

**Comment by kiwicopple** [comment]
Hey @Laplo, CORS is always a bit tricky. Can you let me know:

- What is your server URL?
- What is your client URL? 
- What is the content of `access-control-allow-origin` header in the OPTIONS response?
- Is there any other error logged on your server?

If you have a repo somewhere online I can also spin it up and have a look - just let me know where it is

**Comment by Laplo** [comment]
Hey @kiwicopple 
- My server url is http://localhost:4000/
- My client url is http://localhost:3002/
- It's *
- On my server side I don't have any error

I uploaded a repo here : https://github.com/Laplo/react_postgrest

**Comment by kiwicopple** [comment]
OK found it. tldr: we need to send `PATCH` instead of `patch` to PostgREST for the preflight to succeed.

See the ALLOW header here, which is obviously case sensitive (TIL).

<img width="284" alt="image" src="https://user-images.githubusercontent.com/10214025/73819215-094ba480-482a-11ea-8ca5-ea71deca5410.png">

I'll fix now and close. Thanks for the feedback @Laplo !
