### ISSUE TITLE
ParserError<`Expected identifier at \`${GenericStringError}\``>

### ISSUE THREAD

**Issue by arthur-overlord** [supabase/postgrest-js#542]
# Bug report
- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When using variable in template literals the `'ParserError<`Expected identifier at \`${GenericStringError}\``>'` is shown.

```
const locale = useLocale(); // return oneOf 'en', 'es', 'fr'
const { data, error } = await supabase.from("activities_sector").select(`id, name, ${locale}`);
```

I tried to manually type the data `{ id: number; name: string; [key: string]: string }` without success

## Expected behavior

No typescript typings error, return type should not have this relation.

## Screenshots

<img width="954" alt="Capture d’écran 2024-06-21 à 12 34 46" src="https://github.com/supabase/postgrest-js/assets/167186552/bf79b4f5-a783-49c9-973c-a37f12446fd1">

## System information

- OS: macOS
- Browser: vivaldi
- Version of supabase-js: 2.26.0
- Version of Node.js: 18.20.2

**Comment by avallete** [comment]
Hey there!

It seems like the issue arises because your `${locale}` isn't a literal value when passed as a parameter, as you're attempting to do. Therefore, the type parsing logic cannot properly determine the result of your query.

Let’s break it down with an example:
```ts
const locale: "col1" | "col2" = "col1"; // <- Inferred type is "col1" because TypeScript infers the final value literal.
let other: "col1" | "col2" = "col1"; // <- Inferred type is a union "col1" | "col2" since TypeScript cannot infer the final type as the value can change. Or even `string` if the variable is assigned inside a closure or something
```

Even though `locale` is a union of valid values for your column, it's still a variable. So when you pass it as a TypeScript template for the type parser, it results in something like this:

```ts
id, name, ${"en" | "us" | "fr"}
```

This causes issues with type inference because TypeScript can't predict which column will be selected, and thus, it can't infer the proper return type. At runtime, this will work because the variable’s value will be inserted into the template string, constructing the proper query. 

To resolve this, you need to manually cast the type. One way to do this is by using the `returns()` API as mentioned in the documentation: [Helper Types for Tables and Joins](https://supabase.com/docs/reference/javascript/typescript-support#helper-types-for-tables-and-joins).

In your case, you can write something like this:

```ts
const { data } = await supabase
  .from("activities_sector")
  .select(`id, name, ${locale}`)
  .returns<{
    id: number;
    name: string;
  } & Record<"en" | "us" | "fr", string>>();

// Now, you can access:
data.en;
data.us;
data.fr;
data.id;
data.name;
// However, this will raise an error:
data.never;
```

I hope this helps!
